# Generated by Django 3.2.7 on 2021-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('ingredient', models.CharField(max_length=20, null=True)),
                ('quantity', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('ingridient', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('subscribe', models.CharField(max_length=100, null=True)),
                ('bigcat', models.CharField(max_length=10, null=True)),
                ('smallcat', models.CharField(max_length=20, null=True)),
                ('imageurl', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=10, null=True)),
                ('keyword', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
