# Generated by Django 3.2.7 on 2021-09-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingri', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('subscribe', models.CharField(max_length=100, null=True)),
                ('bigcat', models.CharField(max_length=10, null=True)),
                ('smallcat', models.CharField(max_length=20, null=True)),
                ('imageurl', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=10, null=True)),
                ('keyword', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
