# Generated by Django 3.2.7 on 2021-10-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
