# Generated by Django 3.2.7 on 2021-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_rename_ingridient_ingredient_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mealkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('ranking', models.CharField(max_length=20, null=True)),
                ('mealkit', models.CharField(max_length=50, null=True)),
                ('product', models.CharField(max_length=20, null=True)),
                ('thumbnail', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('brand', models.CharField(max_length=20, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('review_cnt', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
