# Generated by Django 3.2.7 on 2021-10-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_mealkit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('bigcat', models.CharField(max_length=20, null=True)),
                ('keyword', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
