# Generated by Django 3.2.7 on 2021-10-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_ingredientunique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientunique',
            name='bigcat',
            field=models.CharField(choices=[('채소', '채소'), ('정육·계란', '정육·계란'), ('수산·해산·건어물', '수산·해산·건어물'), ('과일·견과·쌀', '과일·견과·쌀')], max_length=20, null=True),
        ),
    ]
