# Generated by Django 3.2.7 on 2021-10-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0006_alter_ingredientunique_bigcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetail',
            name='keyword',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
