# Generated by Django 3.2.7 on 2021-10-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0007_fooddetail_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='weight',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
