# Generated by Django 3.2.7 on 2021-10-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0008_ingredient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='recipe',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
