# Generated by Django 3.2.7 on 2021-10-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0009_food_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
