# Generated by Django 3.2.7 on 2021-10-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0011_starpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Starpoint',
        ),
    ]
