# Generated by Django 3.2.7 on 2021-10-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0012_delete_starpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_point', models.IntegerField(default=3, null=True)),
                ('post_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='articleapp.food')),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
