# Generated by Django 3.2.7 on 2021-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0016_auto_20211030_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starpoint',
            name='post_food',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='starpoint',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
